### ISSUE TITLE
Is it possible to add an inheritance from ITestableWebElement to ITestableWebPage

### ISSUE THREAD

**Issue by KR-7** [Jarga/Alias#1]
Hi,

In the original Alias implementation, ITestableWebPage inherited from ITestableWebElement but it looks like now ITestableWebPage inherits directly from ISearchableWebObject. I'm in the process of converting my testing to use the new version but when I pass in a baseObject of ITestableWebPage it says that it can't convert it (I'm guessing because there's no inheritance).

Thanks,
Kyle

**Comment by Jarga** [comment]
Can you send me a quick example? I might be able to offer another solution. The change to the hierarchy was to better match the logical separation of a page from an element.

**Comment by KR-7** [comment]
During a test I create a new object based on an Ext SmartGrid and when creating that object, I pass in the BaseObject (inherited from WebPage) and a "gridId." The SmartGrid object inherits from the WebElement class:

`public class SmartGrid : WebElement
    {`

Here is the SmartGrid constructor and the `base(baseObject)` is where I'm getting the issue _"cannot convert from 'Aliases.Common.Shared.ITestableWebPage' to 'Aliases.Common.Shared.ITestableWebElement'"_:
 
`public SmartGrid(ITestableWebPage baseObject, string gridId) : base(baseObject)
        {`

And if it's helpful, here is the code to create the SmartGrid object:

`SmartGrid accountManagerListGrid = new SmartGrid(BaseObject, "ctl00_cphMain_spAccouhtManagers_resultsView");`

**Comment by Jarga** [comment]
I see. Here is how a custom web element would be implemented now:

```c#
public class CustomWebElement : WebElement
    {
        public Alias SomeSubElement = new Alias() {Id = "some_sub_element"};
        public CustomWebElement(ITestableWebElement baseObject) : base(baseObject)
        {

        }

        public void TypeInSomeSubElement(string text)
        {
            Type(SomeSubElement, text);
        }
    }
```

And then in the page you could do:

```c#
public class CustomWebPage : WebPage
    {
        public Alias SomeCustomWebElement = new Alias() {Id = "some_web_element"};

        public CustomWebElement CustomWebElement => new CustomWebElement(FindSubElement(SomeCustomWebElement));


        public CustomWebPage(ITestConfiguration testConfig) : base(testConfig)
        {
            EnsureElementLoaded(SomeCustomWebElement, "CustomWebPage loaded", "CustomWebPage failed to load");
        }

        public void TypeInSomeCustomSubElement(string text)
        {
            CustomWebElement.TypeInSomeSubElement(text);
        }
    }
```

The difference now is you don't have to pass around ids anymore.  You would create an Alias from the grid id and when you needed to use the grid you would find it on the page and then use that as the base object.

**Comment by KR-7** [comment]
Okay, that makes sense. I'll have to make some logic changes on my end because my CustomWebElement uses the grid id for a few methods. So I'll have to grab it from `baseObject.Attribute("Id");`

I'm also in the process of converting this same CustomWebElement from the old string based API and that is the more annoying part! lol

Thanks again! I'll let you know how it works!

**Comment by Jarga** [comment]
Sure, also all actions from within the custom WebElement don't have to use the id of the original element anymore since by making the "GridElement" as the base object it will implicitly scope all find calls to that element.  So you might not need that Id anymore.
